name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Build and run JUnit 5 Looming
      run: |
        wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
        source ./install-jdk.sh --url https://download.java.net/java/early_access/loom/2/openjdk-14-loom+2-4_linux-x64_bin.tar.gz
        java src/build/Build.java
        JUNIT='java -Xmx2G --module-path lib:bin/main/modules --module org.junit.platform.console --details SUMMARY --scan-modules'
        $JUNIT --config tests=10000 --config thread=true
        $JUNIT --config tests=10000 --config thread=false
        $JUNIT --config tests=100000 --config thread=false
        # $JUNIT --config tests=1000000 --config thread=false
