name: CI
on: push
jobs:
  build:
    name: "JUnit 5 Looming (${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Build and test JUnit 5 Looming Test Engine
      run: |
        wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
        source ./install-jdk.sh --url https://download.java.net/java/early_access/loom/2/openjdk-16-loom+2-14_linux-x64_bin.tar.gz
        java src/build/Build.java
        echo ::set-env name=JUNIT::"${JAVA_HOME}/bin/java -Xmx2G --module-path bin/main/modules:lib --module org.junit.platform.console --details SUMMARY --scan-modules"
    - name: 'Normal Threads running 10.000 tests'
      run: $JUNIT --config virtual=false --config tests=10000
    - name: 'Normal Threads running 100.000 tests'
      run: $JUNIT --config virtual=false --config tests=100000
    - name: 'Virtual Threads running 10.000 tests'
      run: $JUNIT --config virtual=true --config tests=10000
    - name: 'Virtual Threads running 100.000 tests'
      run: $JUNIT --config virtual=true --config tests=100000
    - name: 'Virtual Threads running 1.000.000 tests'
      run: $JUNIT --config virtual=true --config tests=1000000
